package com.bookbuddy.bookbuddy.Entities;

import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// This is the Book Entity. It represents a book in our application.
// It has a unique ID generated by the database, a title, an author, a price, and a description.
// For returning book information to the client, we use the BookDTO class.
// Jimmy Karoly

@Entity
@Schema(name = "Book", description = "A book entity")
@Table(name = "books")
public class Book {

	@Id
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Unique ID generated by database corresponding to a book", example = "1") 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Long id;

    @Column(name="title")
    @Schema(description = "Title of the book", example = "The Great Gatsby")
    private String title;

    @Schema(description = "Author of the book", example = "F. Scott Fitzgerald")
    @Column(name="author")   
    private String author;

    @Schema(description = "Price of the book", example = "12.99")
    @Column(name="price")
    private BigDecimal price;

    @Schema(description = "Description of the book", example = "A novel about the American Dream")
    @Column(name="description", columnDefinition="TEXT")
    private String description;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public BigDecimal getPrice(){
        return price;
    }

    public void setPrice(BigDecimal price){
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
	public String toString() {
		return "Book [id=" + id + ", title=" + title + ", author=" + author + ", price=" + price + ", description=" + description + "]";
	}

    //Jimmy Karoly

}
