package com.bookbuddy.bookbuddy.Entities;

import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;

//This is the BookCollectionDTO class. It is a Data Transfer Object (DTO) that is used to send book collection information back to the client.
//It has an id, a collection name, and a list of books in the collection.
//Jimmy Karoly

@Schema(name = "BookCollectionDTO", description = "A DTO for a book collection")
public class BookCollectionDTO {

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Unique ID generated by database corresponding to a book collection", example = "1")
    private Long id;
    @Schema(description = "Name of the collection", example = "Favorite Books")
    private String collectionName;
    @Schema(description = "List of books in the collection")
    private List<Book> booksInCollection;

    public static BookCollectionDTO fromEntity(BookCollection collection){
        BookCollectionDTO collectionDTO = new BookCollectionDTO();
        collectionDTO.setId(collection.getId());
        collectionDTO.setCollectionName(collection.getCollectionName());
        collectionDTO.setBooksInCollection(collection.getBooks());
        return collectionDTO;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCollectionName() {
        return collectionName;
    }

    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName;
    }

    public List<Book> getBooksInCollection() {
        return booksInCollection;
    }

    public void setBooksInCollection(List<Book> booksInCollection) {
        this.booksInCollection = booksInCollection;
    }
    
}
