package com.bookbuddy.bookbuddy.Entities;

import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Schema(name = "OrderItem", description = "items in the order")
@Table(name = "order_items")
public class OrderItem {

	public OrderItem(Order order, Book book, BigDecimal itemPrice){
		this.order = order;
		this.book = book;
		this.itemPrice = itemPrice;
	}

	@Id
	@Column(name = "order_item_id")
	@Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Unique ID generated by database corresponding to a user", example = "1")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long orderItemId;

	@ManyToOne
	@Schema(description = "id of the order",example = "00067")
	@JoinColumn(name = "order_id")
	private Order order;
	
	@ManyToOne
	@Schema(description = "id of the book",example = "00089")
	@JoinColumn(name = "book_id")
	private Book book;
	
	@Schema(description = "price of the item",example = "$5.99")
	@Column(name = "itemPrice")
	private BigDecimal itemPrice;

	public Long getOrderItemId() {
		return orderItemId;
	}

	public void setOrderItemId(Long orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public BigDecimal getItemPrice() {
		return itemPrice;
	}

	public void setItemPrice(BigDecimal itemPrice) {
		this.itemPrice = itemPrice;
	}

	public Order getOrder(){
		return this.order;
	}

	public void setOrder(Order order){
		this.order = order;
	}
	

}
