import React, { useState } from "react";

const GenreSelection = () => {
  const [selectedGenres, setSelectedGenres] = useState([]);

  const handleGenreSelection = (genre) => {
    if (selectedGenres.includes(genre)) {
      setSelectedGenres(selectedGenres.filter((g) => g !== genre));
    } else {
      setSelectedGenres([...selectedGenres, genre]);
    }
  };

  // Replace these with your actual genre options
  const genres = [
    '12th Century',
    '15th Century',
    '16th Century',
    '17th Century',
    '18th Century',
    '19th Century',
    '20th Century',
    '21st Century',
    'Abuse',
    'Academia',
    'Academic',
    'Action',
    'Activism',
    'Adhd',
    'Adoption',
    'Adult',
    'Adult Fiction',
    'Adventure',
    'Africa',
    'African American',
    'African American Literature',
    'African Literature',
    'Agriculture',
    'Alchemy',
    'Algeria',
    'Aliens',
    'Alternate History',
    'Alternate Universe',
    'Amazon',
    'American',
    'American Civil War',
    'American History',
    'American Revolution',
    'American Revolutionary War',
    'Americana',
    'Amish',
    'Anarchism',
    'Ancient',
    'Ancient History',
    'Angels',
    'Animal Fiction',
    'Animals',
    'Anthologies',
    'Anthropology',
    'Anti Racist',
    'Apocalyptic',
    'Archaeology',
    'Architecture',
    'Art',
    'Art Design',
    'Art History',
    'Arthurian',
    'Artificial Intelligence',
    'Asexual',
    'Asia',
    'Asian Literature',
    'Astrology',
    'Astronomy',
    'Atheism',
    'Audiobook',
    'Australia',
    'Autistic Spectrum Disorder',
    'Autobiography',
    'Aviation',
    'BDSM',
    'Bande Dessinée',
    'Banned Books',
    'Baseball',
    'Basketball',
    'Batman',
    'Beauty and The Beast',
    'Biblical Fiction',
    'Biography',
    'Biography Memoir',
    'Biology',
    'Birds',
    'Bizarro Fiction',
    'Boarding School',
    'Book Club',
    'Books About Books',
    'Botswana',
    'Brain',
    'Brazil',
    'British Literature',
    'Buddhism',
    'Buisness',
    'Business',
    'Canada',
    'Canadian Literature',
    'Catholic',
    'Cats',
    'Chapter Books',
    'Chemistry',
    'Chick Lit',
    'Childrens',
    'Childrens Classics',
    'China',
    'Chinese Literature',
    'Christian',
    'Christian Fantasy',
    'Christian Fiction',
    'Christian Historical Fiction',
    'Christian Living',
    'Christian Non Fiction',
    'Christian Romance',
    'Christianity',
    'Christmas',
    'Church',
    'Cities',
    'Civil War',
    'Classic Literature',
    'Classical Music',
    'Classics',
    'Clean Romance',
    'Climate Change',
    'Climate Change Fiction',
    'Collections',
    'College',
    'Comedian',
    'Comedy',
    'Comic Book',
    'Comic Strips',
    'Comics',
    'Coming Of Age',
    'Comix',
    'Communication',
    'Computer Science',
    'Conspiracy Theories',
    'Contemporary',
    'Contemporary Romance',
    'Cookbooks',
    'Cooking',
    'Counselling',
    'Counter Culture',
    'Counting',
    'Cozy Mystery',
    'Crafts',
    'Crime',
    'Criticism',
    'Cthulhu Mythos',
    'Culinary',
    'Cults',
    'Cultural',
    'Cyberpunk',
    'Cycling',
    'Czech Literature',
    'Danish',
    'Dark',
    'Dark Fantasy',
    'Dc Comics',
    'Death',
    'Demons',
    'Denmark',
    'Design',
    'Detective',
    'Diary',
    'Diets',
    'Dinosaurs',
    'Disability',
    'Divination',
    'Divorce',
    'Dogs',
    'Dragonlance',
    'Dragons',
    'Drama',
    'Drawing',
    'Dungeons and Dragons',
    'Dutch Literature',
    'Dying Earth',
    'Dystopia',
    'Ecology',
    'Economics',
    'Education',
    'Edwardian',
    'Egypt',
    'Egyptian Literature',
    'Elves',
    'Emotion',
    'Engineering',
    'English Literature',
    'Entrepreneurship',
    'Environment',
    'Epic',
    'Epic Fantasy',
    'Erotic Romance',
    'Erotica',
    'Espionage',
    'Essays',
    'Ethiopia',
    'Eugenics',
    'European History',
    'European Literature',
    'Evolution',
    'Fae',
    'Fairies',
    'Fairy Tale Retellings',
    'Fairy Tales',
    'Faith',
    'Family',
    'Fan Fiction',
    'Fantasy',
    'Fantasy Romance',
    'Far Right',
    'Fat',
    'Fat Acceptance',
    'Fat Studies',
    'Female Authors',
    'Feminism',
    'Femme Femme',
    'Fiction',
    'Fighters',
    'Figure Skating',
    'Film',
    'Finance',
    'Finnish Literature',
    'Fitness',
    'Flash Fiction',
    'Folk Tales',
    'Folklore',
    'Food',
    'Food Writing',
    'Food and Drink',
    'Foodie',
    'Football',
    'Forgotten Realms',
    'Fostering',
    'France',
    'French Literature',
    'French Revolution',
    'Futurism',
    'Futuristic',
    'Games',
    'Gaming',
    'Gardening',
    'Gay',
    'Gay Fiction',
    'Gender',
    'Gender Studies',
    'Genderfluid',
    'Genetics',
    'Geography',
    'Geology',
    'German Literature',
    'Germany',
    'Ghana',
    'Ghost Stories',
    'Ghosts',
    'Global Warming',
    'Go',
    'God',
    'Gods',
    'Gothic',
    'Gothic Horror',
    'Government',
    'Graphic Novels',
    'Graphic Novels Comics',
    'Greece',
    'Greek Mythology',
    'Guidebook',
    'Halloween',
    'Hard Science Fiction',
    'Health',
    'Health Care',
    'Heroic Fantasy',
    'High Fantasy',
    'High School',
    'Hinduism',
    'Hip Hop',
    'Historical',
    'Historical Fantasy',
    'Historical Fiction',
    'Historical Mystery',
    'Historical Romance',
    'History',
    'History Of Science',
    'Hockey',
    'Holiday',
    'Holocaust',
    'Home Economics',
    'Homeschool',
    'Horror',
    'Horse Racing',
    'Horses',
    'How To',
    'Hugo Awards',
    'Humor',
    'Hungarian Literature',
    'Hungary',
    'Illness',
    'India',
    'Indian Literature',
    'Indonesian Literature',
    'Inspirational',
    'International',
    'International Development',
    'International Relations',
    'Internet',
    'Iran',
    'Ireland',
    'Irish Literature',
    'Islam',
    'Israel',
    'Italian Literature',
    'Italy',
    'Japan',
    'Japanese Literature',
    'Jewish',
    'Josei',
    'Journal',
    'Journaling',
    'Journalism',
    'Judaica',
    'Judaism',
    'Juvenile',
    'Kenya',
    'Kids',
    'LGBT',
    'Language',
    'Latin American',
    'Latin American Literature',
    'Law',
    'Lds',
    'Lds Fiction',
    'Lds Non Fiction',
    'Leadership',
    'Lebanon',
    'Legal Thriller',
    'Lesbian',
    'Lesbian Romance',
    'Liberia',
    'Light Novel',
    'Linguistics',
    'Literary Criticism',
    'Literary Fiction',
    'Literature',
    'Logic',
    'Love',
    'Love Inspired',
    'Love Inspired Historical',
    'Love Inspired Suspense',
    'Love Story',
    'Lovecraftian',
    'M F Romance',
    'M M Contemporary',
    'M M F',
    'M M Romance',
    'Magic',
    'Magical Realism',
    'Malawi',
    'Management',
    'Manga',
    'Marathi',
    'Maritime',
    'Marriage',
    'Martial Arts',
    'Mathematics',
    'Mauritius',
    'Media Tie In',
    'Medical',
    'Medicine',
    'Medieval',
    'Medieval History',
    'Medieval Romance',
    'Memoir',
    'Menage',
    'Mental Health',
    'Mental Illness',
    'Mermaids',
    'Metaphysics',
    'Microhistory',
    'Middle Grade',
    'Military Fiction',
    'Military History',
    'Military Romance',
    'Military Science Fiction',
    'Modern',
    'Modern Classics',
    'Money',
    'Monsters',
    'Morocco',
    'Mountaineering',
    'Murder Mystery',
    'Music',
    'Musicals',
    'Musicians',
    'Mystery',
    'Mystery Thriller',
    'Mysticism',
    'Mythology',
    'Native American History',
    'Native Americans',
    'Natural History',
    'Nature',
    'Naval History',
    'Neuroscience',
    'New Adult',
    'New Adult Romance',
    'New Age',
    'New Weird',
    'New York',
    'Nigeria',
    'Nobel Prize',
    'Noir',
    'Nonfiction',
    'Nordic Noir',
    'Novella',
    'Novels',
    'Nursery Rhymes',
    'Nutrition',
    'Occult',
    'Outdoors',
    'Own',
    'Paganism',
    'Pakistan',
    'Palaeontology',
    'Paranormal',
    'Paranormal Romance',
    'Parenting',
    'Personal Development',
    'Personal Finance',
    'Philosophy',
    'Photography',
    'Physics',
    'Picture Books',
    'Pirates',
    'Plantagenet',
    'Plays',
    'Poetry',
    'Poetry Plays',
    'Poland',
    'Police',
    'Polish Literature',
    'Political Science',
    'Politics',
    'Polyamory',
    'Polygamy',
    'Pop Culture',
    'Popular Science',
    'Portugal',
    'Portuguese Literature',
    'Post Apocalyptic',
    'Poverty',
    'Prayer',
    'Prehistoric',
    'Prehistory',
    'Presidents',
    'Princesses',
    'Productivity',
    'Programming',
    'Prostitution',
    'Psychiatry',
    'Psychoanalysis',
    'Psychological Thriller',
    'Psychology',
    'Pulp',
    'Punk',
    'Queer',
    'Rabbits',
    'Race',
    'Read For School',
    'Realistic Fiction',
    'Reference',
    'Regency',
    'Regency Romance',
    'Relationships',
    'Religion',
    'Research',
    'Retellings',
    'Reverse Harem',
    'Robots',
    'Rock N Roll',
    'Roman',
    'Romance',
    'Romania',
    'Romanian Literature',
    'Romantic',
    'Romantic Suspense',
    'Romanticism',
    'Russia',
    'Russian History',
    'Russian Literature',
    'Russian Revolution',
    'Rwanda',
    'Satanism',
    'Scandinavian Literature',
    'School',
    'School Stories',
    'Science',
    'Science Fiction',
    'Science Fiction Fantasy',
    'Science Fiction Romance',
    'Scotland',
    'Seinen',
    'Self Help',
    'Serbian Literature',
    'Sexuality',
    'Shapeshifters',
    'Shojo',
    'Short Stories',
    'Short Story Collection',
    'Sierra Leone',
    'Singularity',
    'Skepticism',
    'Soccer',
    'Social',
    'Social Issues',
    'Social Justice',
    'Social Media',
    'Social Science',
    'Social Work',
    'Society',
    'Sociology',
    'Software',
    'Somalia',
    'South Africa',
    'Southern',
    'Southern Gothic',
    'Space',
    'Space Opera',
    'Spain',
    'Spanish Civil War',
    'Spanish Literature',
    'Speculative Fiction',
    'Spirituality',
    'Splatterpunk',
    'Sports',
    'Sports Romance',
    'Spy Thriller',
    'Star Trek',
    'Star Wars',
    'Steampunk',
    'Storytime',
    'Street Art',
    'Sudan',
    'Superheroes',
    'Superman',
    'Supernatural',
    'Surreal',
    'Survival',
    'Suspense',
    'Sustainability',
    'Sweden',
    'Swedish Literature',
    'Sword and Planet',
    'Sword and Sorcery',
    'Taoism',
    'Tarot',
    'Tasmania',
    'Tea',
    'Teaching',
    'Technical',
    'Technology',
    'Teen',
    'Terrorism',
    'Textbooks',
    'The United States Of America',
    'The World',
    'Theatre',
    'Thelema',
    'Theology',
    'Theory',
    'Thriller',
    'Time Travel',
    'Tragedy',
    'Trains',
    'Transgender',
    'Transport',
    'Travel',
    'Travelogue',
    'True Crime',
    'True Story',
    'Tudor Period',
    'Turkish',
    'Turkish Literature',
    'Tv',
    'Ukraine',
    'Ukrainian Literature',
    'Unfinished',
    'Unicorns',
    'United States',
    'Urban',
    'Urban Fantasy',
    'Urban Planning',
    'Urbanism',
    'Us Presidents',
    'Utopia',
    'Vampires',
    'Vegan',
    'Vegetarian',
    'Victorian',
    'Video Games',
    'War',
    'Weird Fiction',
    'Weird West',
    'Werewolves',
    'Westerns',
    'Wicca',
    'Wildlife',
    'Witchcraft',
    'Witches',
    'Wolves',
    'Womens',
    'Womens Fiction',
    'Womens Studies',
    'World History',
    'World War I',
    'World War II',
    'Writing',
    'Young Adult',
    'Young Adult Contemporary',
    'Young Adult Fantasy',
    'Young Adult Paranormal',
    'Young Adult Romance',
    'Young Readers',
    'Zen',
    'Zimbabwe',
    'Zombies',
  ];
  

  return (
    <div>
      <h2>Select your preferred genres</h2>
      <div>
        {genres.map((genre) => (
          <div key={genre}>
            <label>
              <input
                type="checkbox"
                checked={selectedGenres.includes(genre)}
                onChange={() => handleGenreSelection(genre)}
              />
              {genre}
            </label>
          </div>
        ))}
      </div>
    </div>
  );
};

export default GenreSelection;